#!/usr/bin/env python
import os
import sys

try:
	name = sys.argv[1] + '.py'
except:
	raise ValueError("Name of command file is required")

with open(name, "r+") as file:
	old = file.read()
	file.seek(0)
	file.write("#!/usr/bin/env python\n" + old)
	file.close()

os.system("chmod +x " + name)
os.system("mv " + name + " " + name.replace(".py", ""))
os.system("cp " + str(name[:-3]) + " ~/bin")
os.system(f"rm -rf {name.replace('.py', '')}")