#!/usr/bin/env python
import os
import sys

if len(sys.argv) == 3:
	name = sys.argv[1] + '.py'
else:
	print("You need to name of the python file")
	print("Run '$ commander <python file name>'")
	sys.exit(1)

with open(name, "r+") as file:
	old = file.read()
	file.seek(0)
	file.write("#!/usr/bin/env python3\n" + old)
	file.close()

os.system("chmod +x " + name)
os.system("mv " + name + " " + name.replace(".py", ""))
os.system("cp " + str(name[:-3]) + " ~/bin")
os.system(f"rm -rf {name.replace('.py', '')}")
